make PyAutoGUI default
fishyboteso/fishyboteso pull request #185
Opened 2024-02-12 20:45 UTC by Femi-lawal

Fixed #173

2024-02-23 15:21 UTC, adsau59 requested changes
changes requested

2024-02-23 15:21 UTC, adsau59 commented on fishy/engine/common/screenshot.py
> +    raise Exception("Failed to initialize a screenshot library.")
not a good idea to throw exception, might crash the thread if its not handled, logging and error, and returning None, and handling the None value where this method is used is a much cleaner way of handling errors

2024-02-23 15:21 UTC, adsau59 commented on fishy/engine/common/screenshot.py
> +            return lib_instance
I like the idea of automatically test each lib and use the one which works...

some points to consider...

1. setup() throws exceptions as the screenshot lib being used is unpredictable on some system, so maybe, handle it with try/catch too
2. preferred_lib isn't even used if its not d3dshot, this logic doesn't let user use the library they selected

2024-02-23 15:21 UTC, adsau59 commented on fishy/engine/common/screenshot.py
> +            logging.warning("D3DShot setup failed. Falling back to default method...")
I don't get the reason behind handling d3dshot separately

2024-03-03 17:41 UTC, Femi-lawal commented
@adsau59 Thank you for the review, I've implemented the changes.

2024-03-07 15:55 UTC, adsau59 requested changes
code looks good to me, just need to handle None [here](https://github.com/fishyboteso/fishyboteso/blob/0fdb285aea0d912454699785a8cae6c63d796b95/fishy/engine/common/window_server.py#L38)

2024-03-11 08:11 UTC, Femi-lawal commented
> code looks good to me, just need to handle None [here](https://github.com/fishyboteso/fishyboteso/blob/0fdb285aea0d912454699785a8cae6c63d796b95/fishy/engine/common/window_server.py#L38)

@adsau59 Hi, I've updated screenshot.create() to handle None

2024-03-12 07:25 UTC, merged

2024-03-12 07:25 UTC, adsau59 commented
looks good, thanks for the contribution