Full auto engine
fishyboteso/fishyboteso pull request #66
Opened 2021-04-17 16:36 UTC by adsau59

- rework to use fishyqr instead of ocr
- install required addon automatically
- optimized controls for better user experience 

only change in semifisher:
https://github.com/fishyboteso/fishyboteso/commit/c05355fb7737d255c5b3ff4e43687ac0d44b40e0

2021-04-17 19:28 UTC, SemjonKerner requested changes
You are changing the requirements.txt anyway, could you maybe use d3dshot to get the screenshot instead? It's much faster.
See https://github.com/SemjonKerner/fishyboteso/blob/fishylight/qrtest/fishylight.py#L10
Lines 10, 13 and 30

I did not read the fullfisher files. Can't spend the time understanding them.

2021-04-17 19:28 UTC, SemjonKerner commented on fishy/constants.py
> +fishyqr = ("FishyQR", "https://github.com/fishyboteso/FishyQR/files/6329586/FishyQR.zip", 1)
for sake of sanity, can you please use the correct versions? 100 for fishyqr and 30 for libgps

2021-04-17 19:28 UTC, SemjonKerner commented on fishy/constants.py
> +libgps = ("LibAddonMenu-2.0", "https://cdn.esoui.com/downloads/file601/LibGPS_3_0_3.zip", 1)
the name is a leftover of copy pasting

2021-04-18 06:21 UTC, adsau59 commented
> You are changing the requirements.txt anyway

- Added modules for qr code reading, and a library to get mouse events, 

> could you maybe use d3dshot to get the screenshot instead? It's much faster.

Yeah true, but image grabbing is abstracted in WindowServer which isn't related to full auto... We can create a new PR to implement that optimization

2021-04-18 06:32 UTC, merged