some fixes and additions
fishyboteso/fishyboteso pull request #90
Opened 2021-08-06 13:11 UTC by wabkia

in my quest to add a defense when attacked in fullauto mode, i had to move some things around. the main issue seems to be that sometimes the bot just gets stuck in some state, but that was happening before i made changes :P i think fishing hole detection overall was improved but it also increased the chance that the bot will move on from a pond that it has already cast in.  on a guess i added some rotation when the QR is 'none' and it hasnt stopped because it 'cant find QR' since. not the best fix but its working better than i thought. i accidentally got an old patch in there, 0001-key-change.patch can be deleted.

2021-08-07 21:36 UTC, wabkia commented
could i have changed the 'too close' skip into a deletion for waypoints or as a check before adding into the timeline? yes sounds great right? too bad i was annoyed and rewrote it to use RMB to set the waypoint. its working splendidly and also i can incorporate it back into the auto waypoint loop as a way to add more granular control. i probably need to add it back anyway because anyone with a fishy file previous to the change will be less optimized tho i can probably find a way around that also.

i learned a lot since yesterday and i realized that working with the human jitter, while an excellent idea, was covering up all sorts of issues. i tracked em down and have included them here :)

2021-12-20 09:21 UTC, adsau59 commented
move waypoint changes to other PR and keep this one only for the fighting system

2021-12-20 09:22 UTC, adsau59 requested changes

2021-12-20 09:22 UTC, adsau59 commented on fishy/engine/fullautofisher/engine.py
> +                # self.rotate_back()
dont keep commented code

2021-12-20 09:22 UTC, adsau59 commented on fishy/engine/fullautofisher/engine.py
> +            pass
looks like  you have inverted the if statement, ignore the comment on old commit

2021-12-20 09:22 UTC, adsau59 commented on fishy/engine/fullautofisher/engine.py
> +        #     pass
dont keep commented code pls

2021-12-20 09:26 UTC, adsau59 commented
Hi, sorry for the super late review, was busy with my job and this slipped from my head, thank you for the PR... I have requested a few changes, pls resolve them if they sound ok

2022-02-25 13:09 UTC, SemjonKerner commented
I tried reviewing this, but it is stuffed.

You really should split this up into logical units and create multiple PRs. There is some useful stuff in here, that should probably go into main, but other stuff definitely blocks this PR from getting merged, sorry.

Gonna close this PR in a few weeks, if noone objects. I hope you will consider publishing the best bits as separate PRs.

2022-02-25 13:10 UTC, SemjonKerner requested changes
I tried reviewing this, but it is stuffed.

You really should split this up into logical units and create multiple PRs. There is some useful stuff in here, that should probably go into main, but other stuff definitely blocks this PR from getting merged, sorry.

Gonna close this PR in a few weeks, if noone objects. I hope you will consider publishing the best bits as separate PRs.

2022-02-25 13:10 UTC, SemjonKerner commented on fishy/engine/fullautofisher/engine.py
> +        #     pass
+1

2022-02-25 13:10 UTC, SemjonKerner commented on fishy/engine/fullautofisher/engine.py
> +                time.sleep(0.005)
5ms is to quick to be a reasonable timeout.

2022-02-25 13:10 UTC, SemjonKerner commented on fishy/engine/fullautofisher/mode/recorder.py
> +            logging.warning("QR not found, couldn't record hole")
this warning is covered in the QR engine

2022-03-17 06:07 UTC, adsau59 commented
closing due to inactivity

2022-03-17 06:07 UTC, closed without merging